#!/usr/bin/env python3

import os
import sys

from analyzer import Analyzer
from termcolor import colored
from helpers import get_user_timeline

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @twitter_handle")

    # clean twitter handle formatting
    handle = '@' + sys.argv[1].replace('@', '')

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)

    # retrieve list of 50 tweets and analyze each
    tweets = get_user_timeline(handle, 50)
    
    # handle get_user_timeline errors
    if tweets == None:
        sys.exit("No tweets for {}.".format(handle))
    
    # score and assign sentiment category to each tweet
    for tweet in tweets:
        score = analyzer.analyze(tweet)
        if score > 0.0:
            color = 'green'
            print(' ',end='')
        elif score < 0.0:
            color = 'red'
        else:
            color = 'yellow'
            print(' ',end='')
        
        print(colored(str(score) + ' ' + tweet, color))

if __name__ == "__main__":
    main()